import * as i0 from '@angular/core';
import { input, Component, inject, output, computed, model, signal, effect, ChangeDetectionStrategy } from '@angular/core';
import { Router } from '@angular/router';
import * as i1 from 'primeng/dialog';
import { DialogModule } from 'primeng/dialog';

class LoadingStateComponent {
    size = input('md', ...(ngDevMode ? [{ debugName: "size" }] : /* istanbul ignore next */ []));
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: LoadingStateComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.1.0", version: "21.2.22", type: LoadingStateComponent, isStandalone: true, selector: "tpp-loading-state", inputs: { size: { classPropertyName: "size", publicName: "size", isSignal: true, isRequired: false, transformFunction: null } }, ngImport: i0, template: "<div class=\"tpp-loading-state\" [class]=\"'tpp-loading-state-' + size()\">\n  <svg width=\"100%\" height=\"100%\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n    <path d=\"M48 0H27V9H39V21H48V0Z\" fill=\"#FF6C37\" class=\"tpp-loading-state-path1\"/>\n    <path d=\"M48 27H27V36H39V48H48V27Z\" fill=\"#FF6C37\" class=\"tpp-loading-state-path2\"/>\n    <path d=\"M21 27H0V36H12V48H21V27Z\" fill=\"#FF6C37\" class=\"tpp-loading-state-path3\"/>\n  </svg>\n</div>", styles: [".tpp-loading-state{display:inline-flex;align-items:center;justify-content:center}.tpp-loading-state-sm{width:24px;height:24px}.tpp-loading-state-md{width:48px;height:48px}.tpp-loading-state-lg{width:72px;height:72px}.tpp-loading-state-path1{opacity:0;animation:tppFadeIn1 1.5s infinite}.tpp-loading-state-path2{opacity:0;animation:tppFadeIn2 1.5s infinite}.tpp-loading-state-path3{opacity:0;animation:tppFadeIn3 1.5s infinite}@keyframes tppFadeIn1{0%{opacity:0}25%{opacity:1}75%{opacity:1}to{opacity:0}}@keyframes tppFadeIn2{0%{opacity:0}25%{opacity:0}50%{opacity:1}75%{opacity:1}to{opacity:0}}@keyframes tppFadeIn3{0%{opacity:0}50%{opacity:0}75%{opacity:1}to{opacity:0}}\n"] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: LoadingStateComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-loading-state', template: "<div class=\"tpp-loading-state\" [class]=\"'tpp-loading-state-' + size()\">\n  <svg width=\"100%\" height=\"100%\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n    <path d=\"M48 0H27V9H39V21H48V0Z\" fill=\"#FF6C37\" class=\"tpp-loading-state-path1\"/>\n    <path d=\"M48 27H27V36H39V48H48V27Z\" fill=\"#FF6C37\" class=\"tpp-loading-state-path2\"/>\n    <path d=\"M21 27H0V36H12V48H21V27Z\" fill=\"#FF6C37\" class=\"tpp-loading-state-path3\"/>\n  </svg>\n</div>", styles: [".tpp-loading-state{display:inline-flex;align-items:center;justify-content:center}.tpp-loading-state-sm{width:24px;height:24px}.tpp-loading-state-md{width:48px;height:48px}.tpp-loading-state-lg{width:72px;height:72px}.tpp-loading-state-path1{opacity:0;animation:tppFadeIn1 1.5s infinite}.tpp-loading-state-path2{opacity:0;animation:tppFadeIn2 1.5s infinite}.tpp-loading-state-path3{opacity:0;animation:tppFadeIn3 1.5s infinite}@keyframes tppFadeIn1{0%{opacity:0}25%{opacity:1}75%{opacity:1}to{opacity:0}}@keyframes tppFadeIn2{0%{opacity:0}25%{opacity:0}50%{opacity:1}75%{opacity:1}to{opacity:0}}@keyframes tppFadeIn3{0%{opacity:0}50%{opacity:0}75%{opacity:1}to{opacity:0}}\n"] }]
        }], propDecorators: { size: [{ type: i0.Input, args: [{ isSignal: true, alias: "size", required: false }] }] } });

class NotFoundComponent {
    router = inject(Router);
    showButton = input(true, ...(ngDevMode ? [{ debugName: "showButton" }] : /* istanbul ignore next */ []));
    buttonText = input('Volver al inicio', ...(ngDevMode ? [{ debugName: "buttonText" }] : /* istanbul ignore next */ []));
    homeRoute = input('/', ...(ngDevMode ? [{ debugName: "homeRoute" }] : /* istanbul ignore next */ []));
    goHome() {
        this.router.navigate([this.homeRoute()]);
    }
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: NotFoundComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "21.2.22", type: NotFoundComponent, isStandalone: true, selector: "tpp-not-found", inputs: { showButton: { classPropertyName: "showButton", publicName: "showButton", isSignal: true, isRequired: false, transformFunction: null }, buttonText: { classPropertyName: "buttonText", publicName: "buttonText", isSignal: true, isRequired: false, transformFunction: null }, homeRoute: { classPropertyName: "homeRoute", publicName: "homeRoute", isSignal: true, isRequired: false, transformFunction: null } }, ngImport: i0, template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-search\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">404</h1>\r\n    <h2 class=\"tpp-error-title\">P\u00E1gina no encontrada</h2>\r\n    <p class=\"tpp-error-message\">La p\u00E1gina que busca no existe o fue movida. Verifique la direcci\u00F3n o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:1rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .75rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: NotFoundComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-not-found', template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-search\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">404</h1>\r\n    <h2 class=\"tpp-error-title\">P\u00E1gina no encontrada</h2>\r\n    <p class=\"tpp-error-message\">La p\u00E1gina que busca no existe o fue movida. Verifique la direcci\u00F3n o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:1rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .75rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] }]
        }], propDecorators: { showButton: [{ type: i0.Input, args: [{ isSignal: true, alias: "showButton", required: false }] }], buttonText: [{ type: i0.Input, args: [{ isSignal: true, alias: "buttonText", required: false }] }], homeRoute: [{ type: i0.Input, args: [{ isSignal: true, alias: "homeRoute", required: false }] }] } });

class ServerErrorComponent {
    router = inject(Router);
    showButton = input(true, ...(ngDevMode ? [{ debugName: "showButton" }] : /* istanbul ignore next */ []));
    buttonText = input('Volver al inicio', ...(ngDevMode ? [{ debugName: "buttonText" }] : /* istanbul ignore next */ []));
    homeRoute = input('/', ...(ngDevMode ? [{ debugName: "homeRoute" }] : /* istanbul ignore next */ []));
    goHome() {
        this.router.navigate([this.homeRoute()]);
    }
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: ServerErrorComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "21.2.22", type: ServerErrorComponent, isStandalone: true, selector: "tpp-server-error", inputs: { showButton: { classPropertyName: "showButton", publicName: "showButton", isSignal: true, isRequired: false, transformFunction: null }, buttonText: { classPropertyName: "buttonText", publicName: "buttonText", isSignal: true, isRequired: false, transformFunction: null }, homeRoute: { classPropertyName: "homeRoute", publicName: "homeRoute", isSignal: true, isRequired: false, transformFunction: null } }, ngImport: i0, template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-server\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">500</h1>\r\n    <h2 class=\"tpp-error-title\">Error del servidor</h2>\r\n    <p class=\"tpp-error-message\">Ha ocurrido un error interno. Reintente m\u00E1s tarde o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:.75rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .5rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: ServerErrorComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-server-error', template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-server\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">500</h1>\r\n    <h2 class=\"tpp-error-title\">Error del servidor</h2>\r\n    <p class=\"tpp-error-message\">Ha ocurrido un error interno. Reintente m\u00E1s tarde o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:.75rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .5rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] }]
        }], propDecorators: { showButton: [{ type: i0.Input, args: [{ isSignal: true, alias: "showButton", required: false }] }], buttonText: [{ type: i0.Input, args: [{ isSignal: true, alias: "buttonText", required: false }] }], homeRoute: [{ type: i0.Input, args: [{ isSignal: true, alias: "homeRoute", required: false }] }] } });

class TableStateComponent {
    type = input('empty', ...(ngDevMode ? [{ debugName: "type" }] : /* istanbul ignore next */ []));
    title = input('', ...(ngDevMode ? [{ debugName: "title" }] : /* istanbul ignore next */ []));
    description = input('', ...(ngDevMode ? [{ debugName: "description" }] : /* istanbul ignore next */ []));
    retry = output();
    isLoading = computed(() => this.type() === 'loading', ...(ngDevMode ? [{ debugName: "isLoading" }] : /* istanbul ignore next */ []));
    showRetry = computed(() => this.type() === 'error', ...(ngDevMode ? [{ debugName: "showRetry" }] : /* istanbul ignore next */ []));
    config = computed(() => this.getConfig(this.type()), ...(ngDevMode ? [{ debugName: "config" }] : /* istanbul ignore next */ []));
    displayedTitle = computed(() => this.title() || this.config().title, ...(ngDevMode ? [{ debugName: "displayedTitle" }] : /* istanbul ignore next */ []));
    displayedDescription = computed(() => this.description() || this.config().description, ...(ngDevMode ? [{ debugName: "displayedDescription" }] : /* istanbul ignore next */ []));
    getConfig(type) {
        return this.stateConfig[type] ?? this.stateConfig['empty'];
    }
    stateConfig = {
        loading: {
            icon: '',
            title: 'Cargando datos',
            description: 'Por favor, espere un momento...',
        },
        empty: {
            icon: 'ti-inbox',
            title: 'No hay registros',
            description: 'Crea un nuevo registro para comenzar.',
        },
        'no-results': {
            icon: 'ti-search',
            title: 'No se encontraron resultados',
            description: 'Intente ajustar los filtros de búsqueda.',
        },
        error: {
            icon: 'ti-alert-triangle',
            title: 'Error al cargar los datos',
            description: 'No se pudieron cargar los registros. Inténtelo nuevamente.',
        },
    };
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: TableStateComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "21.2.22", type: TableStateComponent, isStandalone: true, selector: "tpp-table-state", inputs: { type: { classPropertyName: "type", publicName: "type", isSignal: true, isRequired: false, transformFunction: null }, title: { classPropertyName: "title", publicName: "title", isSignal: true, isRequired: false, transformFunction: null }, description: { classPropertyName: "description", publicName: "description", isSignal: true, isRequired: false, transformFunction: null } }, outputs: { retry: "retry" }, ngImport: i0, template: "<div role=\"status\" class=\"tpp-table-state\">\n  @if (isLoading()) {\n    <tpp-loading-state size=\"md\"/>\n  } @else {\n    <div class=\"tpp-table-state-icon\">\n      <i [class]=\"'ti ' + config().icon\"></i>\n    </div>\n  }\n  <p class=\"tpp-table-state-title\">{{ displayedTitle() }}</p>\n  <p class=\"tpp-table-state-description\">{{ displayedDescription() }}</p>\n  @if (showRetry()) {\n    <button class=\"tpp-table-state-button\" (click)=\"retry.emit()\">\n      <i class=\"ti ti-refresh\"></i>\n      Reintentar\n    </button>\n  }\n</div>", styles: [".tpp-table-state{display:flex;flex-direction:column;align-items:center;justify-content:center;width:100%;max-width:24rem;margin:0 auto;padding:2.5rem 1rem;text-align:center}.tpp-table-state-icon{display:inline-flex;align-items:center;justify-content:center;width:4rem;height:4rem;border-radius:9999px;background-color:var(--p-primary-100);color:var(--p-primary-500);font-size:1.875rem;margin-bottom:1.5rem}.tpp-table-state-title{margin:0;font-size:1rem;font-weight:600;color:var(--p-surface-800)}.tpp-table-state-description{margin:.25rem 0 0;font-size:.875rem;color:var(--p-surface-500)}.tpp-table-state-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-table-state-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"], dependencies: [{ kind: "component", type: LoadingStateComponent, selector: "tpp-loading-state", inputs: ["size"] }] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: TableStateComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-table-state', imports: [LoadingStateComponent], template: "<div role=\"status\" class=\"tpp-table-state\">\n  @if (isLoading()) {\n    <tpp-loading-state size=\"md\"/>\n  } @else {\n    <div class=\"tpp-table-state-icon\">\n      <i [class]=\"'ti ' + config().icon\"></i>\n    </div>\n  }\n  <p class=\"tpp-table-state-title\">{{ displayedTitle() }}</p>\n  <p class=\"tpp-table-state-description\">{{ displayedDescription() }}</p>\n  @if (showRetry()) {\n    <button class=\"tpp-table-state-button\" (click)=\"retry.emit()\">\n      <i class=\"ti ti-refresh\"></i>\n      Reintentar\n    </button>\n  }\n</div>", styles: [".tpp-table-state{display:flex;flex-direction:column;align-items:center;justify-content:center;width:100%;max-width:24rem;margin:0 auto;padding:2.5rem 1rem;text-align:center}.tpp-table-state-icon{display:inline-flex;align-items:center;justify-content:center;width:4rem;height:4rem;border-radius:9999px;background-color:var(--p-primary-100);color:var(--p-primary-500);font-size:1.875rem;margin-bottom:1.5rem}.tpp-table-state-title{margin:0;font-size:1rem;font-weight:600;color:var(--p-surface-800)}.tpp-table-state-description{margin:.25rem 0 0;font-size:.875rem;color:var(--p-surface-500)}.tpp-table-state-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-table-state-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] }]
        }], propDecorators: { type: [{ type: i0.Input, args: [{ isSignal: true, alias: "type", required: false }] }], title: [{ type: i0.Input, args: [{ isSignal: true, alias: "title", required: false }] }], description: [{ type: i0.Input, args: [{ isSignal: true, alias: "description", required: false }] }], retry: [{ type: i0.Output, args: ["retry"] }] } });

class UnauthorizedComponent {
    router = inject(Router);
    showButton = input(true, ...(ngDevMode ? [{ debugName: "showButton" }] : /* istanbul ignore next */ []));
    buttonText = input('Volver al inicio', ...(ngDevMode ? [{ debugName: "buttonText" }] : /* istanbul ignore next */ []));
    homeRoute = input('/', ...(ngDevMode ? [{ debugName: "homeRoute" }] : /* istanbul ignore next */ []));
    goHome() {
        this.router.navigate([this.homeRoute()]);
    }
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: UnauthorizedComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "21.2.22", type: UnauthorizedComponent, isStandalone: true, selector: "tpp-unauthorized", inputs: { showButton: { classPropertyName: "showButton", publicName: "showButton", isSignal: true, isRequired: false, transformFunction: null }, buttonText: { classPropertyName: "buttonText", publicName: "buttonText", isSignal: true, isRequired: false, transformFunction: null }, homeRoute: { classPropertyName: "homeRoute", publicName: "homeRoute", isSignal: true, isRequired: false, transformFunction: null } }, ngImport: i0, template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-lock\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">401</h1>\r\n    <h2 class=\"tpp-error-title\">No autorizado</h2>\r\n    <p class=\"tpp-error-message\">No tiene permisos para acceder a esta p\u00E1gina. Contacte al administrador o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:.75rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .5rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: UnauthorizedComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-unauthorized', template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-lock\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">401</h1>\r\n    <h2 class=\"tpp-error-title\">No autorizado</h2>\r\n    <p class=\"tpp-error-message\">No tiene permisos para acceder a esta p\u00E1gina. Contacte al administrador o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:.75rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .5rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] }]
        }], propDecorators: { showButton: [{ type: i0.Input, args: [{ isSignal: true, alias: "showButton", required: false }] }], buttonText: [{ type: i0.Input, args: [{ isSignal: true, alias: "buttonText", required: false }] }], homeRoute: [{ type: i0.Input, args: [{ isSignal: true, alias: "homeRoute", required: false }] }] } });

class VideoTutorialModalComponent {
    url = input.required(...(ngDevMode ? [{ debugName: "url" }] : /* istanbul ignore next */ []));
    visible = model(false, ...(ngDevMode ? [{ debugName: "visible" }] : /* istanbul ignore next */ []));
    cargandoVideo = signal(true, ...(ngDevMode ? [{ debugName: "cargandoVideo" }] : /* istanbul ignore next */ []));
    constructor() {
        effect(() => {
            if (this.visible()) {
                this.cargandoVideo.set(true);
                setTimeout(() => {
                    this.cargandoVideo.set(false);
                }, 2000);
            }
        });
    }
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: VideoTutorialModalComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "21.2.22", type: VideoTutorialModalComponent, isStandalone: true, selector: "tpp-video-tutorial-modal", inputs: { url: { classPropertyName: "url", publicName: "url", isSignal: true, isRequired: true, transformFunction: null }, visible: { classPropertyName: "visible", publicName: "visible", isSignal: true, isRequired: false, transformFunction: null } }, outputs: { visible: "visibleChange" }, ngImport: i0, template: "<p-dialog\r\n  [(visible)]=\"visible\"\r\n  header=\"Video tutorial\"\r\n  [modal]=\"true\"\r\n  [maximizable]=\"true\"\r\n  [dismissableMask]=\"false\"\r\n  draggable=\"false\"\r\n  contentStyleClass=\"p-0 overflow-hidden rounded-b-xl\"\r\n  [position]=\"'top'\"\r\n  [style]=\"{ width: '56rem', 'min-height': cargandoVideo() ? '28rem' : 'auto' }\">\r\n  @if (cargandoVideo()) {\r\n    <div class=\"flex flex-col items-center justify-center py-16 gap-4 min-h-[28rem]\">\r\n      <tpp-loading-state size=\"md\" />\r\n      <p class=\"text-gray-400 text-sm\">Cargando video tutorial...</p>\r\n    </div>\r\n  } @else {\r\n    <div class=\"aspect-video\">\r\n      <video [src]=\"url()\" controls class=\"w-full h-full bg-black object-contain\"></video>\r\n    </div>\r\n  }\r\n</p-dialog>\r\n", styles: [""], dependencies: [{ kind: "ngmodule", type: DialogModule }, { kind: "component", type: i1.Dialog, selector: "p-dialog", inputs: ["hostName", "header", "draggable", "resizable", "contentStyle", "contentStyleClass", "modal", "closeOnEscape", "dismissableMask", "rtl", "closable", "breakpoints", "styleClass", "maskStyleClass", "maskStyle", "showHeader", "blockScroll", "autoZIndex", "baseZIndex", "minX", "minY", "focusOnShow", "maximizable", "keepInViewport", "focusTrap", "transitionOptions", "maskMotionOptions", "motionOptions", "closeIcon", "closeAriaLabel", "closeTabindex", "minimizeIcon", "maximizeIcon", "closeButtonProps", "maximizeButtonProps", "visible", "style", "position", "role", "appendTo", "content", "contentTemplate", "footerTemplate", "closeIconTemplate", "maximizeIconTemplate", "minimizeIconTemplate", "headlessTemplate"], outputs: ["onShow", "onHide", "visibleChange", "onResizeInit", "onResizeEnd", "onDragEnd", "onMaximize"] }, { kind: "component", type: LoadingStateComponent, selector: "tpp-loading-state", inputs: ["size"] }], changeDetection: i0.ChangeDetectionStrategy.OnPush });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: VideoTutorialModalComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-video-tutorial-modal', changeDetection: ChangeDetectionStrategy.OnPush, imports: [DialogModule, LoadingStateComponent], template: "<p-dialog\r\n  [(visible)]=\"visible\"\r\n  header=\"Video tutorial\"\r\n  [modal]=\"true\"\r\n  [maximizable]=\"true\"\r\n  [dismissableMask]=\"false\"\r\n  draggable=\"false\"\r\n  contentStyleClass=\"p-0 overflow-hidden rounded-b-xl\"\r\n  [position]=\"'top'\"\r\n  [style]=\"{ width: '56rem', 'min-height': cargandoVideo() ? '28rem' : 'auto' }\">\r\n  @if (cargandoVideo()) {\r\n    <div class=\"flex flex-col items-center justify-center py-16 gap-4 min-h-[28rem]\">\r\n      <tpp-loading-state size=\"md\" />\r\n      <p class=\"text-gray-400 text-sm\">Cargando video tutorial...</p>\r\n    </div>\r\n  } @else {\r\n    <div class=\"aspect-video\">\r\n      <video [src]=\"url()\" controls class=\"w-full h-full bg-black object-contain\"></video>\r\n    </div>\r\n  }\r\n</p-dialog>\r\n" }]
        }], ctorParameters: () => [], propDecorators: { url: [{ type: i0.Input, args: [{ isSignal: true, alias: "url", required: true }] }], visible: [{ type: i0.Input, args: [{ isSignal: true, alias: "visible", required: false }] }, { type: i0.Output, args: ["visibleChange"] }] } });

// Componentes

/**
 * Generated bundle index. Do not edit.
 */

export { LoadingStateComponent, NotFoundComponent, ServerErrorComponent, TableStateComponent, UnauthorizedComponent, VideoTutorialModalComponent };
//# sourceMappingURL=tpp-lib-ui.mjs.map
