import * as i0 from '@angular/core';
import { inject, input, Component, output, computed } from '@angular/core';
import { Router } from '@angular/router';

class NotFoundComponent {
    router = inject(Router);
    showButton = input(true, ...(ngDevMode ? [{ debugName: "showButton" }] : /* istanbul ignore next */ []));
    buttonText = input('Volver al inicio', ...(ngDevMode ? [{ debugName: "buttonText" }] : /* istanbul ignore next */ []));
    homeRoute = input('/', ...(ngDevMode ? [{ debugName: "homeRoute" }] : /* istanbul ignore next */ []));
    goHome() {
        this.router.navigate([this.homeRoute()]);
        console.log('Navigating to home route:', this.homeRoute());
    }
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: NotFoundComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "21.2.22", type: NotFoundComponent, isStandalone: true, selector: "tpp-not-found", inputs: { showButton: { classPropertyName: "showButton", publicName: "showButton", isSignal: true, isRequired: false, transformFunction: null }, buttonText: { classPropertyName: "buttonText", publicName: "buttonText", isSignal: true, isRequired: false, transformFunction: null }, homeRoute: { classPropertyName: "homeRoute", publicName: "homeRoute", isSignal: true, isRequired: false, transformFunction: null } }, ngImport: i0, template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-search\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">404</h1>\r\n    <h2 class=\"tpp-error-title\">P\u00E1gina no encontrada</h2>\r\n    <p class=\"tpp-error-message\">La p\u00E1gina que busca no existe o fue movida. Verifique la direcci\u00F3n o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:1rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .75rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: NotFoundComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-not-found', template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-search\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">404</h1>\r\n    <h2 class=\"tpp-error-title\">P\u00E1gina no encontrada</h2>\r\n    <p class=\"tpp-error-message\">La p\u00E1gina que busca no existe o fue movida. Verifique la direcci\u00F3n o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:1rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .75rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] }]
        }], propDecorators: { showButton: [{ type: i0.Input, args: [{ isSignal: true, alias: "showButton", required: false }] }], buttonText: [{ type: i0.Input, args: [{ isSignal: true, alias: "buttonText", required: false }] }], homeRoute: [{ type: i0.Input, args: [{ isSignal: true, alias: "homeRoute", required: false }] }] } });

class UnauthorizedComponent {
    router = inject(Router);
    showButton = input(true, ...(ngDevMode ? [{ debugName: "showButton" }] : /* istanbul ignore next */ []));
    buttonText = input('Volver al inicio', ...(ngDevMode ? [{ debugName: "buttonText" }] : /* istanbul ignore next */ []));
    homeRoute = input('/', ...(ngDevMode ? [{ debugName: "homeRoute" }] : /* istanbul ignore next */ []));
    goHome() {
        this.router.navigate([this.homeRoute()]);
    }
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: UnauthorizedComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "21.2.22", type: UnauthorizedComponent, isStandalone: true, selector: "tpp-unauthorized", inputs: { showButton: { classPropertyName: "showButton", publicName: "showButton", isSignal: true, isRequired: false, transformFunction: null }, buttonText: { classPropertyName: "buttonText", publicName: "buttonText", isSignal: true, isRequired: false, transformFunction: null }, homeRoute: { classPropertyName: "homeRoute", publicName: "homeRoute", isSignal: true, isRequired: false, transformFunction: null } }, ngImport: i0, template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-lock\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">401</h1>\r\n    <h2 class=\"tpp-error-title\">No autorizado</h2>\r\n    <p class=\"tpp-error-message\">No tiene permisos para acceder a esta p\u00E1gina. Contacte al administrador o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:.75rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .5rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: UnauthorizedComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-unauthorized', template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-lock\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">401</h1>\r\n    <h2 class=\"tpp-error-title\">No autorizado</h2>\r\n    <p class=\"tpp-error-message\">No tiene permisos para acceder a esta p\u00E1gina. Contacte al administrador o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:.75rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .5rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] }]
        }], propDecorators: { showButton: [{ type: i0.Input, args: [{ isSignal: true, alias: "showButton", required: false }] }], buttonText: [{ type: i0.Input, args: [{ isSignal: true, alias: "buttonText", required: false }] }], homeRoute: [{ type: i0.Input, args: [{ isSignal: true, alias: "homeRoute", required: false }] }] } });

class ServerErrorComponent {
    router = inject(Router);
    showButton = input(true, ...(ngDevMode ? [{ debugName: "showButton" }] : /* istanbul ignore next */ []));
    buttonText = input('Volver al inicio', ...(ngDevMode ? [{ debugName: "buttonText" }] : /* istanbul ignore next */ []));
    homeRoute = input('/', ...(ngDevMode ? [{ debugName: "homeRoute" }] : /* istanbul ignore next */ []));
    goHome() {
        this.router.navigate([this.homeRoute()]);
    }
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: ServerErrorComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "21.2.22", type: ServerErrorComponent, isStandalone: true, selector: "tpp-server-error", inputs: { showButton: { classPropertyName: "showButton", publicName: "showButton", isSignal: true, isRequired: false, transformFunction: null }, buttonText: { classPropertyName: "buttonText", publicName: "buttonText", isSignal: true, isRequired: false, transformFunction: null }, homeRoute: { classPropertyName: "homeRoute", publicName: "homeRoute", isSignal: true, isRequired: false, transformFunction: null } }, ngImport: i0, template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-server\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">500</h1>\r\n    <h2 class=\"tpp-error-title\">Error del servidor</h2>\r\n    <p class=\"tpp-error-message\">Ha ocurrido un error interno. Reintente m\u00E1s tarde o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:.75rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .5rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: ServerErrorComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-server-error', template: "<div class=\"tpp-error-container\">\r\n  <div class=\"tpp-error-card\">\r\n    <div class=\"tpp-error-icon\">\r\n      <i class=\"ti ti-server\"></i>\r\n    </div>\r\n    <h1 class=\"tpp-error-code\">500</h1>\r\n    <h2 class=\"tpp-error-title\">Error del servidor</h2>\r\n    <p class=\"tpp-error-message\">Ha ocurrido un error interno. Reintente m\u00E1s tarde o regrese al inicio.</p>\r\n    @if (showButton()) {\r\n      <button class=\"tpp-error-button\" (click)=\"goHome()\">\r\n        {{ buttonText() }}\r\n      </button>\r\n    }\r\n  </div>\r\n</div>\r\n", styles: [".tpp-error-container{display:flex;justify-content:center;align-items:center;min-height:100vh;padding:1rem;background-color:var(--p-surface-50);box-sizing:border-box}.tpp-error-card{display:flex;flex-direction:column;align-items:center;text-align:center;max-width:28rem;width:100%;padding:3rem 2rem;background-color:#fff;border:1px solid var(--p-surface-100);border-radius:.75rem;box-shadow:0 20px 25px -5px #9da3a91a,0 10px 10px -5px #9da3a90a;animation:tpp-error-fade-up .4s ease-out forwards}@keyframes tpp-error-fade-up{0%{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.tpp-error-icon{display:inline-flex;align-items:center;justify-content:center;width:5rem;height:5rem;border-radius:50%;background-color:var(--p-primary-50);color:var(--p-primary-500);font-size:3rem;margin-bottom:1.5rem}.tpp-error-code{font-size:5rem;font-weight:900;color:var(--p-surface-900);margin:0;line-height:1}.tpp-error-title{font-size:1.5rem;font-weight:600;color:var(--p-surface-700);margin:1rem 0 .5rem}.tpp-error-message{font-size:.875rem;line-height:1.5;color:var(--p-surface-500);margin:0}.tpp-error-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-error-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] }]
        }], propDecorators: { showButton: [{ type: i0.Input, args: [{ isSignal: true, alias: "showButton", required: false }] }], buttonText: [{ type: i0.Input, args: [{ isSignal: true, alias: "buttonText", required: false }] }], homeRoute: [{ type: i0.Input, args: [{ isSignal: true, alias: "homeRoute", required: false }] }] } });

class LoadingComponent {
    size = input('md', ...(ngDevMode ? [{ debugName: "size" }] : /* istanbul ignore next */ []));
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: LoadingComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.1.0", version: "21.2.22", type: LoadingComponent, isStandalone: true, selector: "tpp-loading", inputs: { size: { classPropertyName: "size", publicName: "size", isSignal: true, isRequired: false, transformFunction: null } }, ngImport: i0, template: "<div class=\"tpp-loading\" [class]=\"'tpp-loading-' + size()\">\r\n  <svg width=\"100%\" height=\"100%\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\r\n    <path d=\"M48 0H27V9H39V21H48V0Z\" fill=\"#FF6C37\" class=\"tpp-loading-path1\"/>\r\n    <path d=\"M48 27H27V36H39V48H48V27Z\" fill=\"#FF6C37\" class=\"tpp-loading-path2\"/>\r\n    <path d=\"M21 27H0V36H12V48H21V27Z\" fill=\"#FF6C37\" class=\"tpp-loading-path3\"/>\r\n  </svg>\r\n</div>\r\n", styles: [".tpp-loading{display:inline-flex;align-items:center;justify-content:center}.tpp-loading-sm{width:24px;height:24px}.tpp-loading-md{width:48px;height:48px}.tpp-loading-lg{width:72px;height:72px}.tpp-loading-path1{opacity:0;animation:tppFadeIn1 1.5s infinite}.tpp-loading-path2{opacity:0;animation:tppFadeIn2 1.5s infinite}.tpp-loading-path3{opacity:0;animation:tppFadeIn3 1.5s infinite}@keyframes tppFadeIn1{0%{opacity:0}25%{opacity:1}75%{opacity:1}to{opacity:0}}@keyframes tppFadeIn2{0%{opacity:0}25%{opacity:0}50%{opacity:1}75%{opacity:1}to{opacity:0}}@keyframes tppFadeIn3{0%{opacity:0}50%{opacity:0}75%{opacity:1}to{opacity:0}}\n"] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: LoadingComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-loading', template: "<div class=\"tpp-loading\" [class]=\"'tpp-loading-' + size()\">\r\n  <svg width=\"100%\" height=\"100%\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\r\n    <path d=\"M48 0H27V9H39V21H48V0Z\" fill=\"#FF6C37\" class=\"tpp-loading-path1\"/>\r\n    <path d=\"M48 27H27V36H39V48H48V27Z\" fill=\"#FF6C37\" class=\"tpp-loading-path2\"/>\r\n    <path d=\"M21 27H0V36H12V48H21V27Z\" fill=\"#FF6C37\" class=\"tpp-loading-path3\"/>\r\n  </svg>\r\n</div>\r\n", styles: [".tpp-loading{display:inline-flex;align-items:center;justify-content:center}.tpp-loading-sm{width:24px;height:24px}.tpp-loading-md{width:48px;height:48px}.tpp-loading-lg{width:72px;height:72px}.tpp-loading-path1{opacity:0;animation:tppFadeIn1 1.5s infinite}.tpp-loading-path2{opacity:0;animation:tppFadeIn2 1.5s infinite}.tpp-loading-path3{opacity:0;animation:tppFadeIn3 1.5s infinite}@keyframes tppFadeIn1{0%{opacity:0}25%{opacity:1}75%{opacity:1}to{opacity:0}}@keyframes tppFadeIn2{0%{opacity:0}25%{opacity:0}50%{opacity:1}75%{opacity:1}to{opacity:0}}@keyframes tppFadeIn3{0%{opacity:0}50%{opacity:0}75%{opacity:1}to{opacity:0}}\n"] }]
        }], propDecorators: { size: [{ type: i0.Input, args: [{ isSignal: true, alias: "size", required: false }] }] } });

class TableStateComponent {
    type = input('vacio', ...(ngDevMode ? [{ debugName: "type" }] : /* istanbul ignore next */ []));
    titulo = input('', ...(ngDevMode ? [{ debugName: "titulo" }] : /* istanbul ignore next */ []));
    descripcion = input('', ...(ngDevMode ? [{ debugName: "descripcion" }] : /* istanbul ignore next */ []));
    reintentar = output();
    cargando = computed(() => this.type() === 'cargando', ...(ngDevMode ? [{ debugName: "cargando" }] : /* istanbul ignore next */ []));
    mostrarReintentar = computed(() => this.type() === 'error', ...(ngDevMode ? [{ debugName: "mostrarReintentar" }] : /* istanbul ignore next */ []));
    configuracion = computed(() => this.obtenerConfiguracion(this.type()), ...(ngDevMode ? [{ debugName: "configuracion" }] : /* istanbul ignore next */ []));
    tituloMostrado = computed(() => this.titulo() || this.configuracion().titulo, ...(ngDevMode ? [{ debugName: "tituloMostrado" }] : /* istanbul ignore next */ []));
    descripcionMostrada = computed(() => this.descripcion() || this.configuracion().descripcion, ...(ngDevMode ? [{ debugName: "descripcionMostrada" }] : /* istanbul ignore next */ []));
    obtenerConfiguracion(tipo) {
        return this.estadoConfig[tipo] ?? this.estadoConfig['vacio'];
    }
    estadoConfig = {
        cargando: {
            icono: '',
            titulo: 'Cargando datos',
            descripcion: 'Por favor, espere un momento...',
        },
        vacio: {
            icono: 'ti-inbox',
            titulo: 'No hay registros',
            descripcion: 'Crea un nuevo registro para comenzar.',
        },
        'sin-resultados': {
            icono: 'ti-search',
            titulo: 'No se encontraron resultados',
            descripcion: 'Intente ajustar los filtros de búsqueda.',
        },
        error: {
            icono: 'ti-alert-triangle',
            titulo: 'Error al cargar los datos',
            descripcion: 'No se pudieron cargar los registros. Inténtelo nuevamente.',
        },
    };
    static ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: TableStateComponent, deps: [], target: i0.ɵɵFactoryTarget.Component });
    static ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "21.2.22", type: TableStateComponent, isStandalone: true, selector: "tpp-table-state", inputs: { type: { classPropertyName: "type", publicName: "type", isSignal: true, isRequired: false, transformFunction: null }, titulo: { classPropertyName: "titulo", publicName: "titulo", isSignal: true, isRequired: false, transformFunction: null }, descripcion: { classPropertyName: "descripcion", publicName: "descripcion", isSignal: true, isRequired: false, transformFunction: null } }, outputs: { reintentar: "reintentar" }, ngImport: i0, template: "<div role=\"status\" class=\"tpp-table-state\">\n  @if (cargando()) {\n    <tpp-loading size=\"md\"/>\n  } @else {\n    <div class=\"tpp-table-state-icon\">\n      <i [class]=\"'ti ' + configuracion().icono\"></i>\n    </div>\n  }\n  <p class=\"tpp-table-state-titulo\">{{ tituloMostrado() }}</p>\n  <p class=\"tpp-table-state-descripcion\">{{ descripcionMostrada() }}</p>\n  @if (mostrarReintentar()) {\n    <button class=\"tpp-table-state-button\" (click)=\"reintentar.emit()\">\n      <i class=\"ti ti-refresh\"></i>\n      Reintentar\n    </button>\n  }\n</div>\n", styles: [".tpp-table-state{display:flex;flex-direction:column;align-items:center;justify-content:center;width:100%;max-width:24rem;margin:0 auto;padding:2.5rem 1rem;text-align:center}.tpp-table-state-icon{display:inline-flex;align-items:center;justify-content:center;width:4rem;height:4rem;border-radius:9999px;background-color:var(--p-primary-100);color:var(--p-primary-500);font-size:1.875rem;margin-bottom:1.5rem}.tpp-table-state-titulo{margin:0;font-size:1rem;font-weight:600;color:var(--p-surface-800)}.tpp-table-state-descripcion{margin:.25rem 0 0;font-size:.875rem;color:var(--p-surface-500)}.tpp-table-state-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-table-state-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"], dependencies: [{ kind: "component", type: LoadingComponent, selector: "tpp-loading", inputs: ["size"] }] });
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "21.2.22", ngImport: i0, type: TableStateComponent, decorators: [{
            type: Component,
            args: [{ selector: 'tpp-table-state', imports: [LoadingComponent], template: "<div role=\"status\" class=\"tpp-table-state\">\n  @if (cargando()) {\n    <tpp-loading size=\"md\"/>\n  } @else {\n    <div class=\"tpp-table-state-icon\">\n      <i [class]=\"'ti ' + configuracion().icono\"></i>\n    </div>\n  }\n  <p class=\"tpp-table-state-titulo\">{{ tituloMostrado() }}</p>\n  <p class=\"tpp-table-state-descripcion\">{{ descripcionMostrada() }}</p>\n  @if (mostrarReintentar()) {\n    <button class=\"tpp-table-state-button\" (click)=\"reintentar.emit()\">\n      <i class=\"ti ti-refresh\"></i>\n      Reintentar\n    </button>\n  }\n</div>\n", styles: [".tpp-table-state{display:flex;flex-direction:column;align-items:center;justify-content:center;width:100%;max-width:24rem;margin:0 auto;padding:2.5rem 1rem;text-align:center}.tpp-table-state-icon{display:inline-flex;align-items:center;justify-content:center;width:4rem;height:4rem;border-radius:9999px;background-color:var(--p-primary-100);color:var(--p-primary-500);font-size:1.875rem;margin-bottom:1.5rem}.tpp-table-state-titulo{margin:0;font-size:1rem;font-weight:600;color:var(--p-surface-800)}.tpp-table-state-descripcion{margin:.25rem 0 0;font-size:.875rem;color:var(--p-surface-500)}.tpp-table-state-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.75rem;padding:.6rem 1.5rem;background-color:var(--p-primary-500);color:#fff;border:1px solid transparent;border-radius:.5rem;font-size:.875rem;font-weight:600;cursor:pointer;transition:background-color .2s ease-in-out,border-color .2s ease-in-out}.tpp-table-state-button:hover{background-color:var(--p-primary-600);border-color:var(--p-primary-700)}\n"] }]
        }], propDecorators: { type: [{ type: i0.Input, args: [{ isSignal: true, alias: "type", required: false }] }], titulo: [{ type: i0.Input, args: [{ isSignal: true, alias: "titulo", required: false }] }], descripcion: [{ type: i0.Input, args: [{ isSignal: true, alias: "descripcion", required: false }] }], reintentar: [{ type: i0.Output, args: ["reintentar"] }] } });

// Componentes

/**
 * Generated bundle index. Do not edit.
 */

export { LoadingComponent, NotFoundComponent, ServerErrorComponent, TableStateComponent, UnauthorizedComponent };
//# sourceMappingURL=tpp-lib-ui.mjs.map
